---
params: 
  - { name: "com.huawei.hms.client.appid", required: "1", showName: "huawei_appid", desc: "华为的APPID", bWriteInManifest: "1", bWriteInClient: "0"  }
  - { name: "com.huawei.hms.client.cpid", required: "1", showName: "huawei_cpid", desc: "华为的PAYID", bWriteInManifest: "1", bWriteInClient: "0"  }
  

operations: 
  - { step: "1", type: "mergeManifest", from: "SDKManifest.xml", to: "AndroidManifest.xml"  }
  - { step: "2", type: "copyRes", from: "assets", to: "assets"  }
  - { step: "3", type: "copyRes", from: "libs", to: "lib"  }
  - { step: "4", type: "copyRes", from: "res", to: "res"  }

plugins:
  - { name: "com.platform.uhuawei.PlatFormHuaWei", type: "1", desc: "华为的用户登录接口" }
  - { name: "com.platform.uhuawei.PlatFormHuaWeiPay", type: "2", desc: "华为的用户支付接口" }

sdkVersionCode:  "1"
sdkVersionName:  "3.6.3"


sdkAPK: "SDKHuaWei.apk"
sdkPlatformName: "huawei"