---
params: 
  - { name: "KUPAI_APPID", required: "1", showName: "KUPAI_APPID", desc: "酷派的APPID", bWriteInManifest: "1", bWriteInClient: "0"  }

operations: 
  - { step: "1", type: "mergeManifest", from: "SDKManifest.xml", to: "AndroidManifest.xml"  }
  - { step: "2", type: "copyRes", from: "libs", to: "lib"  }
  - { step: "3", type: "copyRes", from: "res", to: "res"  }

plugins:
  - { name: "com.platform.ukupai.PlatFormKuPai", type: "1", desc: "酷派的用户登录接口" }
  - { name: "com.platform.ukupai.PlatFormKuPaiPay", type: "2", desc: "酷派的用户支付接口" }

sdkVersionCode:  "1"
sdkVersionName:  "3.6.3"


sdkAPK: "SDKKuPai.apk"
sdkPlatformName: "coolpad"