---
params: 
  - { name: "MEIZU_APPID", required: "1", showName: "MEIZU_APPID", desc: "MEIZU的APPID", bWriteInManifest: "1", bWriteInClient: "0"  }
  - { name: "MEIZU_APPKEY", required: "1", showName: "MEIZU_APPKEY", desc: "MEIZU的APPKEY", bWriteInManifest: "1", bWriteInClient: "0"  }

operations: 
  - { step: "1", type: "mergeManifest", from: "SDKManifest.xml", to: "AndroidManifest.xml"  }
  - { step: "2", type: "copyRes", from: "assets", to: "assets"  }
  - { step: "3", type: "copyRes", from: "libs", to: "lib"  }

plugins:
  - { name: "com.platform.umeizu.PlatFormMeizu", type: "1", desc: "魅族的用户登录接口" }
  - { name: "com.platform.umeizu.PlatFormMeizuPay", type: "2", desc: "魅族的用户支付接口" }

sdkVersionCode:  "1"
sdkVersionName:  "3.6.3"


sdkAPK: "SDKMeizu.apk"
sdkPlatformName: "mz"