---
params: 
  - { name: "MEITU_APPID", required: "1", showName: "MEITU_APPID", desc: "美图的APPID", bWriteInManifest: "1", bWriteInClient: "0"  }
  - { name: "MEITU_APPKEY", required: "1", showName: "MEITU_APPKEY", desc: "美图的APPKEY", bWriteInManifest: "1", bWriteInClient: "0"  }
  - { name: "AVALON_APPLICATION_PROXY_NAME", required: "1", showName: "AVALON_APPLICATION_PROXY_NAME", desc: "美图的APPLICATION_PROXY", bWriteInManifest: "1", bWriteInClient: "0"  }

operations: 
  - { step: "1", type: "mergeManifest", from: "SDKManifest.xml", to: "AndroidManifest.xml"  }
  - { step: "2", type: "copyRes", from: "assets", to: "assets" }
  - { step: "3", type: "copyRes", from: "res", to: "res"  }
  - { step: "4", type: "copyRes", from: "libs", to: "lib"  }

plugins:
  - { name: "com.platform.umeitu.PlatFormMeitu", type: "1", desc: "美图的用户登录接口" }
  - { name: "com.platform.umeitu.PlatFormPayMeitu", type: "2", desc: "美图的用户支付接口" }

sdkVersionCode:  "1"
sdkVersionName:  "3.6.3"


sdkAPK: "SDKMeitu.apk"
sdkPlatformName: "meitu"