---
params: 
  - { name: "MI_APPID", required: "1", showName: "MI_APPID", desc: "小米的APPID", bWriteInManifest: "1", bWriteInClient: "0"  }
  - { name: "MI_APPKEY", required: "1", showName: "MI_APPKEY", desc: "小米的APPKEY", bWriteInManifest: "1", bWriteInClient: "0"  }
  - { name: "AVALON_APPLICATION_PROXY_NAME", required: "1", showName: "AVALON_APPLICATION_PROXY_NAME", desc: "小米的MI_APPLICATION_PROXY", bWriteInManifest: "1", bWriteInClient: "0"  }

operations: 
  - { step: "1", type: "mergeManifest", from: "SDKManifest.xml", to: "AndroidManifest.xml"  }
  - { step: "2", type: "copyRes", from: "res", to: "res"  }
  - { step: "3", type: "copyRes", from: "libs", to: "lib"  }

plugins:
  - { name: "com.platform.umi.PlatFormMi", type: "1", desc: "小米的用户登录接口" }
  - { name: "com.platform.umi.PlatFormPayMi", type: "2", desc: "小米的用户支付接口" }

sdkVersionCode:  "1"
sdkVersionName:  "3.6.3"


sdkAPK: "SDKMi.apk"
sdkPlatformName: "xiaomi"